#! /bin/sh

while [ $# -gt 0 ]; do
    case "$1" in
        --verbose)
            verbose=2
            ;;
        --verbose=*)
            verbose="${1#*=}"
            ;;
        --dropdb)
            dropdb=1
            ;;
        --createdb)
            createdb=1
            ;;
        *)
            printf "***************************\n"
            printf "* Error: Invalid argument.*\n"
            printf "***************************\n"
            exit 1
    esac
    shift
done

# --verbose=1 by default
export verbose=${verbose:-1}

if [ "$verbose" = 0 ] || [ "$verbose" = 1 ] ; then
    exec >/dev/null
fi

directory=$(dirname $0)

export PGHOST=${PGHOST:-localhost}
export PGPORT=${PGPORT:-5432}
export PGDATABASE=${PGDATABASE:-fhirbase}
export PGUSER=${PGUSER:-fhirbase}
export PGPASSWORD=${PGPASSWORD:-your_password}

export PG_SCHEMA=${PG_SCHEMA:-perf}
export OTHER_DATABASE=${OTHER_DATABASE:-postgres}

export NUMBER_OF_PATIENTS=${NUMBER_OF_PATIENTS:-1000}
export RAND_SEED=${RAND_SEED:-0.21}

if [ "$verbose" = 3 ] ; then
    echo "PGHOST=$PGHOST"
    echo "PGDATABASE=$PGDATABASE"
    echo "PGPORT=$PGPORT"
    echo "PGUSER=$PGUSER"
    echo "PGPASSWORD=$PGPASSWORD"

    echo "PG_SCHEMA=$PG_SCHEMA"
    echo "OTHER_DATABASE=$OTHER_DATABASE"

    echo "NUMBER_OF_PATIENTS=$NUMBER_OF_PATIENTS"
    echo "RAND_SEED=$RAND_SEED"
fi

if [ "$createdb" = 1 ] ; then
    if [ "$dropdb" = 1 ] ; then
        echo Drop $PGDATABASE database.
        read -r -d '' sql << EOF
DROP DATABASE IF EXISTS $PGDATABASE;
EOF
        psql $OTHER_DATABASE --command="$sql" || exit 1
    fi

    echo Crate $PGDATABASE database.
    read -r -d '' sql << EOF
CREATE DATABASE $PGDATABASE WITH OWNER $PGUSER ENCODING = 'UTF8';
EOF
    psql $OTHER_DATABASE --command="$sql" || exit 1

    echo Install Fhirbase into $PGDATABASE database.
    psql --file="$directory"/../tmp/build.sql || exit 1
else
    echo Assume that database $PGDATABASE.$PG_SCHEMA \
         contains installed Fhirbase.
fi

echo Load temporary tables into $PGDATABASE.$PG_SCHEMA \
     from "$directory"/data.
psql --file="$directory"/load.sql || exit 1

read -r -d '' sql << EOF
SET plv8.start_proc = 'plv8_init';
SELECT fhir_create_storage('{"resourceType": "Organization"}'::json);
EOF
psql --command="$sql" || exit 1

echo Create generation functions in $PGDATABASE.$PG_SCHEMA.
psql --file="$directory"/generate.sql || exit 1

if [ "$verbose" != 0 ] ; then
    exec > /dev/tty
fi

echo Run performance tests.
read -r -d '' sql << EOF
SET plv8.start_proc = 'plv8_init';
SELECT generate($NUMBER_OF_PATIENTS, $RAND_SEED);
EOF
psql --command="$sql" || exit 1
